name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Google Maps API key
        env:
          MAPS_API_KEY: ${{ secrets.SET }}
        run: |
          sed "s|__MAPS_API_KEY__|$MAPS_API_KEY|g" index.template.html > index.html

      - name: Upload artifact / deploy
        # your deploy step here (e.g. GitHub Pages, Netlify, etc.)
